language: python
fast_finish: true

python: 
  - 3.5
  - 3.6
  - "3.7-dev"

os:
  - linux
  
env: FC=gfortran-6

group: travis_latest
  
git:
  depth: 3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-6


before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update > /dev/null;
      brew install gcc || true > /dev/null;
      brew link --overwrite gcc > /dev/null;
      export FC=gfortran;
      brew install opencoarrays > /dev/null;
    fi

install:
  - pip -q install -e .[tests]
  
  - cd bin
  - cmake ..
  - make
  - make test
  - cd ..

script: 
  - pytest -sv
  - flake8
  - mypy . --ignore-missing-imports

after_success: 
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    coverage run tests/test_all.py;
    coveralls;
    fi
    
after_failure:
  - ctest -V

