language: python
sudo: required
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

python:
  - 3.5
  - 3.6
  - 3.7

os:
  - linux
  
env: FC=gfortran-6

# FIXME: temporary for travis xenial
#addons:
#  apt:
#    sources: ubuntu-toolchain-r-test
#    packages: gfortran-6


before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update > /dev/null;
      brew install gcc > /dev/null || brew link --overwrite gcc > /dev/null;
      export FC=gfortran;
      brew install opencoarrays > /dev/null;
    else
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
      sudo apt-get update -q;
      sudo apt-get install -yq gfortran-6;
    fi

install:
  - pip install -e .[tests]

  - cd bin
  - cmake ..
  - cmake --build .

script:
  - ctest -V
  - cd ..
  
  - pytest -sv
  - flake8
  - mypy . --ignore-missing-imports

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pytest --cov;
    coveralls;
    fi

